### ISSUE TITLE
Type mismatch found in file -> inc /migrate.php

### ISSUE THREAD

**Issue by emaralive** [buddypress/bp-classic#27]
The type mismatch occurs on line 71 of inc/migrate.php. The mismatch is due to "string" vs "integer" in the "in_array" function due to the parameter "strict" set to true. The needle ($item->object_id) is a "string" and the haystack ($nav_menu_item_ids) is an array of "integers", thus what would be qualified menu items fail to be updated. Changing line 71:

From:
`if ( $old_post_type !== $item->object || ! in_array( $item->object_id, $nav_menu_item_ids, true ) ) {`

To:
`if ( $old_post_type !== $item->object || ! in_array( (int) $item->object_id, $nav_menu_item_ids, true ) ) {`

This would suffice but, I'll leave it up to the appropriate person to apply an appropriate fix.
`

**Comment by imath** [comment]
Hi @emaralive Thanks for raising this issue. I will look at it more deeply asap.
