### ISSUE TITLE
The rtMedia plugin appears to cause an error notice to be thrown

### ISSUE THREAD

**Issue by emaralive** [buddypress/bp-classic#28]
### The environment at the time:
WP 6.4.1
BP 12.0.0.beta4
PHP 7.4.33
[rtMedia plugin 4.6.15](https://wordpress.org/plugins/buddypress-media/) 
Classic plugin 1.1.0

### Active components:
Community Members, Extended Profiles, Account Settings, Friend Connections, Private Messaging, Activity Streams, Notifications, User Groups, Site Tracking

### Active template pack:
BuddyPress Nouveau

### Parent theme:
Twenty Eleven

**Note:** Any WP branch compatiple with BP 12.0.0, either BP template pack, and any compatible WP theme is sufficient to replicate this issue.

The key factors are "**User Groups**" enabled, the **rtMedia** plugin active and visiting a group page, e.g., site.url/groups/name_of_group/, will result with the following error notice to be thrown:

**`Notice: Trying to get property 'inc_dir' of non-object in /wp-content/plugins/bp-classic/inc/core/widgets.php on line 122`**

Offhand, it looks like there is an issue with timing of when the property "**inc_dir**" is available. Additionally, while on group page any cause for a page refresh, e.g, clicking on a group menu item, causes the same error to be thrown.

**Comment by imath** [comment]
Thanks a lot for your report. Looking at it asap.

**Comment by imath** [comment]
This is what I get:
`[11-Nov-2023 10:58:55 UTC] PHP Warning:  Attempt to read property "inc_dir" on bool in /.../bp-classic/inc/core/widgets.php on line 122`

I confirm it's not happening without rtMedia active. But I believe it's revealing a BP Classic issue. We should only check if the current BuddyPress version is 12.0 or up once. I see we are doing it each time `bp_classic()` is called.

I'll submit a PR asap.

**Comment by imath** [comment]
Actually after digging more into it, rtMedia is doing something wrong. I just reported an issue about it:
https://github.com/rtCamp/rtMedia/issues/2009

**Comment by emaralive** [comment]
I see, OK sounds good!
