### ISSUE TITLE
Groups Pagination

### ISSUE THREAD

**Issue by lmstearn** [buddypress/bp-classic#34]
With bbPress, the older pages of a group can never be reached, e.g. clicking the page two button on 
https://mysite.com/groups/administrators/forum/
gets the following url in the browser url field, but not the load of the second page.
https://mysite.com/groups/administrators/forum/page/2/
Without the page two button visibly registering any activation.
Thanks.

**Comment by imath** [comment]
Hi thanks for your report. I’ll look at it asap 👍

imath
https://imathi.eu
________________________________
De : Laurie Stearn ***@***.***>
Envoyé : Thursday, December 28, 2023 5:09:39 AM
À : buddypress/bp-classic ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [buddypress/bp-classic] Groups Pagination (Issue #34)


The older pages of a group can never be reached, e.g. clicking the page two button on
https://mysite.com/groups/administrators/forum/
gets the following url in the browser url field, but not the load of the second page.
https://mysite.com/groups/administrators/forum/page/2/
Without the page two button visibly registering any activation.
Thanks.

**Comment by imath** [comment]
Hi @lmstearn 

This should be handled by the bbPress plugin imho. Here's a way to have it working: https://gist.github.com/imath/24fdfa1b8625477e93c0daa0d90b2a44
