### ISSUE TITLE
Incompatible with Elementor

### ISSUE THREAD

**Issue by Bamstian** [buddypress/bp-classic#48]
With BP Classic active I am no longer able to edit my Elementor-Templates. I get an 500 error. If I disable BP Classic Elementor works as usual.

**Comment by imath** [comment]
Hi sorry to read about it. What the 500 error says into your error_log ?

**Comment by Bamstian** [comment]
Elementor says "Preview could not be loaded - Error 500"
If I click the link (domain.tld/?elementor_library=zugriffsschutz&elementor-preview=161&ver=1712316715&preview-debug)

`removed by Bamstian`

But there is noting in debug.log (wp-content)

**Comment by imath** [comment]
The error trace you pasted is not containing any reference to `wp-content/plugins/buddypress` or `wp-content/plugins/bp-classic`. So none of these are involved into this error.

If `wp-content/debug.log` doesn't include anything about the error (or if this file does not exist), you need to ask your host provider where is located the `error_log` file of your site. Without the error trace I cannot help you more.

**Comment by Bamstian** [comment]
Thanks for your answer,

we just deactivated your plugin and everything works now. Things that we missed afterwards were programmed within the functions.php. I just wanted to tell you that there might be a conflict using "BuddyX", Elementor Pro and BP Classic.

Kind regards from Berlin,
Basti
